Red wash
merative/spm-toolbox pull request #6
Opened 2023-11-03 11:22 UTC by huangjien

2023-11-07 17:00 UTC, ourboy requested changes

2023-11-07 17:00 UTC, ourboy commented on .devcontainer/Dockerfile
> +#     && apt-get -y install --no-install-recommends <your-package-list-here>
add a new line

2023-11-07 17:00 UTC, ourboy commented on .devcontainer/devcontainer.json
> +  }
add a new line

2023-11-07 17:00 UTC, ourboy commented on .github/workflows/release.yml
> +        api_key: ${{ secrets.GALAXY_TOKEN }}
add a new line

2023-11-07 17:00 UTC, ourboy commented on galaxy.yml
> +version: 1.0.2
I would move this to version 1.1.0 or 2.0.0, clean break

2023-11-09 10:06 UTC, ourboy approved these changes

2023-11-09 11:02 UTC, martinccummins approved these changes
LGTM

2023-11-09 11:06 UTC, merged